version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.24
    working_directory: /home/stackage
    steps:
      - checkout
      - restore_cache:
          key: cache-lts-12.24
      - run: sudo apt update
      - run: sudo apt -y install libncurses5-dev libncursesw5-dev
      - run: stack --no-terminal --system-ghc build --haddock --test --only-dependencies
      - save_cache:
          key: cache-lts-12.24
          paths:
            - ~/.stack
      - run: stack --no-terminal --system-ghc install --haddock --test
